<a href="https://colab.research.google.com/github/tpals213/ict/blob/main/1_2_pytorch_basic_using.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensor Basic Usage  

- Create Tensor
- Indexing, Joinging, Slicing
- Initializaion
- Math Operation

In [4]:
# Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) --> (0, 1) 사이의 실수형 값을 랜덤값으로 발생함
# sizes : 1차원갯수, 2차원 행렬갯수 등 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x

tensor([[0.6138, 0.7472, 0.0319],
        [0.7762, 0.7777, 0.0323]])

In [5]:
# torch.randn(sizes) --> Z(0, 1)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
x = torch.randn(2, 3)
x

tensor([[ 1.5020, -0.3568, -0.5635],
        [ 0.8474, -0.8446, -0.1826]])

In [6]:
# torch.randperm(n) --> permutation of 0 ~ n
x =  torch.randperm(5)
x

tensor([4, 2, 1, 3, 0])

# torch 에서 랜덤값으로 텐서 생성
1. torch.rand() : 0과 1 사이의 실수형 숫자 균등 생성
2. torch.rand_like() : 사이즈를 튜플로 입력 X, 기존의 텐서로 정의
3. torch.randn() : 평균이 0이고 표준편차가 1인 정규분포를 이용해서 생성
4. torch.randn_like() : 기존의 텐서를 사용해서 같은 텐서를 생성
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성
6. torch.randint_like() : 텐서 이용, 같은 텐서 생성
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤 생성