<a href="https://colab.research.google.com/github/tpals213/DeepLearnig/blob/main/1_2_pytorch_basic_using.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tensor Basic Usage  

- Create Tensor
- Indexing, Joinging, Slicing
- Initializaion
- Math Operation

In [2]:
# Create Tensor
# 1) random numbers
import torch

# torch.rand(sizes) --> (0, 1) 사이의 실수형 값을 랜덤값으로 발생함
# sizes : 1차원갯수, 2차원 행렬갯수 등 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)
x

tensor([[0.5518, 0.4918, 0.1209],
        [0.2815, 0.2556, 0.7772]])

In [ ]:
# torch.randn(sizes) --> Z(0, 1)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 생성
x = torch.randn(2, 3)
x

tensor([[ 1.5020, -0.3568, -0.5635],
        [ 0.8474, -0.8446, -0.1826]])

In [ ]:
# torch.randperm(n) --> permutation of 0 ~ n
x =  torch.randperm(5)
x

tensor([4, 2, 1, 3, 0])

# 1) torch 에서 랜덤값으로 텐서 생성
1. torch.rand() : 0과 1 사이의 실수형 숫자 균등 생성
2. torch.rand_like() : 사이즈를 튜플로 입력 X, 기존의 텐서로 정의
3. torch.randn() : 평균이 0이고 표준편차가 1인 정규분포를 이용해서 생성
4. torch.randn_like() : 기존의 텐서를 사용해서 같은 텐서를 생성
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성
6. torch.randint_like() : 텐서 이용, 같은 텐서 생성
7. torch.randperm() : 주어진 범위 내의 정수를 랜덤 생성

# 2) zeros, ones, arange

In [3]:
# torch.zeros(2, 3) --> [[0, 0, 0], ... ,[0, 0, 0]]
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# torch.ones(2, 3) --> [[1, 1, 1], ... ,[1, 1, 1]]
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# torch.arange(start, end, step=1)
x = torch.arange(0, 3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

# 3) Tensor Data Type

In [7]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2, 3)
x

tensor([[1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
x = torch.FloatTensor([12, 35])
x

tensor([12., 35.])

In [9]:
# tensor.type_as(tensor_type)
# 기존 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

# 4) Numpy to Tensor, Tensor to Numpy

In [10]:
import numpy as np

# torch.from_numpy(ndarray) --> Tensor
x1 = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array([1, 2, 3, 4, 5, 6]))
x2 = torch.from_numpy(x1)
x1, x2

(array([[1, 2, 3],
        [4, 5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [11]:
# torch.numpy() --> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

# 5) Tensor on CPU & CPU

In [12]:
x = torch.FloatTensor([[1, 2, 3,], [4, 5, 6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

# 6) Tensor size

In [14]:
# tensor.size() --> 인덱스값
x = torch.FloatTensor(10, 12, 3, 3)
x.size()[:]

torch.Size([10, 12, 3, 3])

# 2. Indexing, Slicing, Joining
1) Indexing

In [15]:
# torch.index_select(input, dim, index)
x = torch.rand(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3]))
x, out

(tensor([[0.5494, 0.7025, 0.2788],
         [0.2612, 0.8756, 0.7390],
         [0.3767, 0.8241, 0.2131],
         [0.6657, 0.8180, 0.9964]]),
 tensor([[0.5494, 0.7025, 0.2788],
         [0.6657, 0.8180, 0.9964]]))

In [16]:
# python indexing 사용 가능
x[:, 0], x[0, :], x[0:2, 0:2]

(tensor([0.5494, 0.2612, 0.3767, 0.6657]),
 tensor([0.5494, 0.7025, 0.2788]),
 tensor([[0.5494, 0.7025],
         [0.2612, 0.8756]]))

In [20]:
# torch.masked_select(input, mask)
x = torch.randn(2, 3)
mask = torch.BoolTensor([[0, 0, 1], [0, 1, 0]])
out = torch.masked_select(x, mask)

x, mask, out

(tensor([[-0.0532,  0.7617,  0.5104],
         [ 0.4914, -0.2266, -0.5336]]),
 tensor([[False, False,  True],
         [False,  True, False]]),
 tensor([ 0.5104, -0.2266]))

2) Joining

In [23]:
# torch.cat(seq, dim = 0)
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
y = torch.FloatTensor([[-1, -2, -3], [-4, -5, -6]])

z1 = torch.cat([x, y], dim=0) # dim=0 (행), 아래에 합쳐짐
z2 = torch.cat([x, y], dim=1) # dim=1 (열), 옆으로 합쳐짐
z1, z2

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [25]:
# torch.stack(sequence, dim=0) --> 새로운 차원으로 추가
x = torch.FloatTensor(([1, 2, 3], [4, 5, 6])) # (2, 3) shape
x_stack = torch.stack([x, x, x, x], dim=0) #(4, 2, 3) shape

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

3) Slicing

In [26]:
# torch.chunk(tensor, chunks, dim=0)
x_1, x_2 = torch.chunk(z1, 2, dim=0)  # dim=0 이면 행을 2개로 분할
x_1, x_2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]))

In [27]:
y_1, y_2, y_3 = torch.chunk(z1, 3, dim=1)  # dim=1 이면 열을 3개로 분할
y_1, y_2, y_3

(tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]),
 tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [30]:
# torch.split(tensor, split_size, dim=0)
x1, x2 = torch.split(z1, 2, dim=0)
y1 = torch.split(z1, 2, dim=1) # 3개 열을 2개로 분리한 경우

z1, x1, x2,y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 (tensor([[ 1.,  2.],
          [ 4.,  5.],
          [-1., -2.],
          [-4., -5.]]),
  tensor([[ 3.],
          [ 6.],
          [-3.],
          [-6.]])))

4) squeezing

In [31]:
# torch.squeeze(input, dim=None)  # 숫자가 1인 차원을 제거

x1 = torch.FloatTensor(10, 1, 3, 14)
# 차원(dimension) 의 개념
# 10 : batch size (데이터 한 묶음당 들어 있는 데이터(x, y)쌍의 갯수)
# 1 : channel size
# 3 : width image size
# 14 : height image size

x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 14]), torch.Size([10, 3, 14]))

In [32]:
# torch,unsqueeze(input, dim=None) --> # 숫자가 1인 차원을 추가
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0) # dim=0 이면 첫번째 위치에 추가

x1.size(), x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

# 3. Initializaion

In [40]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3, 4), a=0, b=9)  # a에서 b사이의 값으로 초기화한다
x2 = init.normal_(torch.FloatTensor(3, 4), std=0.2)  # 표준편차가 0.2 적용해서 초기화
x3 = init.constant_(torch.FloatTensor(3, 4), 3.145)  # 지정된 상수값으로 초기화

x1, x2, x3

(tensor([[2.0369, 0.2522, 1.1093, 5.8574],
         [2.5507, 7.7975, 2.4841, 0.7690],
         [6.4022, 5.1426, 4.1259, 2.2690]]),
 tensor([[-0.0455,  0.0809, -0.0357,  0.2544],
         [ 0.3656, -0.1692, -0.0310, -0.0335],
         [-0.0224, -0.3464,  0.0037, -0.1840]]),
 tensor([[3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450]]))

# 4. Math Operations
1) Arithmetic operation

In [43]:
# torch.add()
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
add = torch.add(x1, x2)

add, x1+x2, x1 - x2

(tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [45]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.add(x1, 10)

x1, x2, x1+10

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]))

In [46]:
# toch.mul() 곱하기
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
mul = torch.mul(x1, x2)
mul, x1*x2

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [47]:
# toch.div() 나누기
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.div(x1, 5)

x1, x2, x1/5

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]))

2) Other MAth Operations

In [51]:
# torch.pow(input, exponent)
x1 = torch.FloatTensor(3, 4)

x1, torch.pow(x1, 2), x1**2

(tensor([[1.3033e-14, 3.0892e-41, 1.0842e-19, 1.7000e+00],
         [2.0000e+00, 1.7750e+00, 1.0842e-19, 1.8250e+00],
         [0.0000e+00, 1.8750e+00, 2.0000e+00, 1.9000e+00]]),
 tensor([[1.6986e-28, 0.0000e+00, 1.1755e-38, 2.8900e+00],
         [4.0000e+00, 3.1506e+00, 1.1755e-38, 3.3306e+00],
         [0.0000e+00, 3.5156e+00, 4.0000e+00, 3.6100e+00]]),
 tensor([[1.6986e-28, 0.0000e+00, 1.1755e-38, 2.8900e+00],
         [4.0000e+00, 3.1506e+00, 1.1755e-38, 3.3306e+00],
         [0.0000e+00, 3.5156e+00, 4.0000e+00, 3.6100e+00]]))

In [55]:
# torch.exp(tensor, out=None)
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
out = torch.exp(x1)

x1, out

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[  2.7183,   7.3891,  20.0855],
         [ 54.5981, 148.4132, 403.4288]]))

In [54]:
# torch.log(tensor, out=None)
x1 = torch.FloatTensor(3, 4)
out = torch.log(x1)

x1, out

(tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[     -inf,      -inf,      -inf,      -inf],
         [     -inf,      -inf,      -inf,      -inf],
         [-103.2789,      -inf,      -inf,      -inf]]))

3) Matrix operation

In [57]:
# torch.mm(mat1, mat2)
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
out = torch.mm(x1, x2)

out, x1@x2

(tensor([[6.3564e+16, 0.0000e+00, 2.8948e-08, 0.0000e+00, 0.0000e+00],
         [4.0988e-13, 0.0000e+00, 1.8666e-37, 0.0000e+00, 0.0000e+00],
         [3.9808e+16, 5.1608e-34, 1.8114e-08, 0.0000e+00, 0.0000e+00]]),
 tensor([[6.3564e+16, 0.0000e+00, 2.8948e-08, 0.0000e+00, 0.0000e+00],
         [4.0988e-13, 0.0000e+00, 1.8666e-37, 0.0000e+00, 0.0000e+00],
         [3.9808e+16, 5.1608e-34, 1.8114e-08, 0.0000e+00, 0.0000e+00]]))

In [58]:
# torch.bmm(batch1, batch2) --> batch 행렬곱 연산
# 맨 앞의 batch 는 차원을 유지하면서, 뒤 요소들의 행렬 곱 연산

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
out = torch.bmm(x1, x2)

out.size()

torch.Size([10, 3, 5])

In [60]:
# torch.dot(tensor1, tensor2) : 백터의 내적을 구함

x1 = torch.FloatTensor([1, 2, 3, 4])
x2 = torch.FloatTensor([2, 3, 4, 5])

torch.dot(x1, x2)

tensor(40.)

In [63]:
# torch.t(matrix) : transposed matrix (텐서의 전치 연산)
# 행과 열을 바꿈

x1 = torch.FloatTensor(3, 4)

x1, x1.t()

(tensor([[2.0597e+06, 3.0885e-41, 4.5702e+30, 4.5155e-41],
         [8.9683e-44, 0.0000e+00, 1.1210e-43, 0.0000e+00],
         [3.0483e+20, 7.0065e-45, 1.3452e-43, 0.0000e+00]]),
 tensor([[2.0597e+06, 8.9683e-44, 3.0483e+20],
         [3.0885e-41, 0.0000e+00, 7.0065e-45],
         [4.5702e+30, 1.1210e-43, 1.3452e-43],
         [4.5155e-41, 0.0000e+00, 0.0000e+00]]))

In [66]:
# torch.transpose(input, dim_0, dim_2)
# 바꿀 차원을 2개 지정함
# 텐서 내부의 차원간 바꾸기

x1 = torch.FloatTensor(10, 3, 4)

# 1차원과 2차원을 서로 바꿈
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1, 2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [ ]:
# torch,eig(input, eigenvectors=False)
# 고유값(eigen_value), 고유벡터
x1 = torch.FloatTensor(4, 4)

import torch.linalg as linal

x1, linalg.eig(x1, True)