<a href="https://colab.research.google.com/github/tpals213/DeepLearnig/blob/main/2_3_lr_variable_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. import required libraries

In [2]:
 import torch
 from torch.autograd import Variable

# 2. Tensor vs Variable
1) Declartion

In [3]:
x_tensor = torch.Tensor(3, 4)
x_tensor

tensor([[2.7604e+20, 1.5766e-19, 1.1513e-38, 3.0697e-41],
        [1.5653e-42, 3.0697e-41, 6.2792e-42, 0.0000e+00],
        [2.5948e-17, 4.3471e-41, 2.5948e-17, 4.3471e-41]])

In [6]:
x_variable = Variable(x_tensor)
x_variable

tensor([[2.7604e+20, 1.5766e-19, 1.1513e-38, 3.0697e-41],
        [1.5653e-42, 3.0697e-41, 6.2792e-42, 0.0000e+00],
        [2.5948e-17, 4.3471e-41, 2.5948e-17, 4.3471e-41]])

Variable 은 autogradient 가능함<br>
Pytorch 0.4 이상에서는 Tensor 에 Variable 이 통합되고, Variabe은 deprecated
Tensor 만 사용  
2) Variable of a Variable

In [7]:
# data 속성
x_variable.data

tensor([[2.7604e+20, 1.5766e-19, 1.1513e-38, 3.0697e-41],
        [1.5653e-42, 3.0697e-41, 6.2792e-42, 0.0000e+00],
        [2.5948e-17, 4.3471e-41, 2.5948e-17, 4.3471e-41]])

In [8]:
# grad 속성 : 값에 대한 gradient
# Variable 생성시 초기화되면서, gradient 도 같이 정의
print(x_variable.grad)

None


In [9]:
# requires_grad 속성 : 값에 대한 gradient 요구시 사용함
print(x_variable.requires_grad) # 속성의 설정값 확인 : False
# gradient 가 계싼이 안된 상태

False


In [10]:
# gradient 에 대한 연산을 수행하게 함 : True
x_variable = Variable(x_tensor, requires_grad = True)
x_variable.requires_grad

True

In [11]:
# volatile 속성 : 최소 메모리 사용에 대한 설정
# requires_grad 가 False 이면, volatile 도 자동 False 가 됨
x_variable = Variable(x_tensor, volatile=True)
x_variable.grad, x_variable.requires_grad, x_variable.volatile

<ipython-input-11-6cd144ec761a>:3: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x_variable = Variable(x_tensor, volatile=True)
<ipython-input-11-6cd144ec761a>:4: UserWarning: volatile was removed (Variable.volatile is always False)
  x_variable.grad, x_variable.requires_grad, x_variable.volatile


(None, False, False)

# 3. Graph & Variables

In [12]:
# create graph
x = Variable(torch.FloatTensor(3, 4), requires_grad=True)
y = x**2 + 4*x
z = 2*y + 3

x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

backward(gradient, retain_graph, create_graph, retain_variables)  
현재 값 w, r, t, graph 에 대한 gradient 계산 함수  
역전파 알고리즘 적용된 계산함수  


In [13]:
# 위의 z 값으로 x 의 gradient 를 계산해 냄
loss = torch.FloatTensor(3, 4)
z.backward(loss)

print(x.grad)
y.grad, z.grad

tensor([[0.0000e+00, 0.0000e+00, 6.1642e+32, 5.7718e+23],
        [1.2613e-18, 8.2048e-08, 5.2505e-06, 2.4217e+13],
        [8.6702e-08, 1.3445e-03, 3.2369e+27,        inf]])


<ipython-input-13-1e201076fae7>:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  y.grad, z.grad


(None, None)